//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/committerpb/block_query.proto

package committerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNumber) Reset() {
	*x = BlockNumber{}
	mi := &file_api_committerpb_block_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNumber) ProtoMessage() {}

func (x *BlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_block_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNumber.ProtoReflect.Descriptor instead.
func (*BlockNumber) Descriptor() ([]byte, []int) {
	return file_api_committerpb_block_query_proto_rawDescGZIP(), []int{0}
}

func (x *BlockNumber) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type TxID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxID) Reset() {
	*x = TxID{}
	mi := &file_api_committerpb_block_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxID) ProtoMessage() {}

func (x *TxID) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_block_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxID.ProtoReflect.Descriptor instead.
func (*TxID) Descriptor() ([]byte, []int) {
	return file_api_committerpb_block_query_proto_rawDescGZIP(), []int{1}
}

func (x *TxID) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_api_committerpb_block_query_proto protoreflect.FileDescriptor

const file_api_committerpb_block_query_proto_rawDesc = "" +
	"\n" +
	"!api/committerpb/block_query.proto\x12\vcommitterpb\"%\n" +
	"\vBlockNumber\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x1b\n" +
	"\x04TxID\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txIdB8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_block_query_proto_rawDescOnce sync.Once
	file_api_committerpb_block_query_proto_rawDescData []byte
)

func file_api_committerpb_block_query_proto_rawDescGZIP() []byte {
	file_api_committerpb_block_query_proto_rawDescOnce.Do(func() {
		file_api_committerpb_block_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_block_query_proto_rawDesc), len(file_api_committerpb_block_query_proto_rawDesc)))
	})
	return file_api_committerpb_block_query_proto_rawDescData
}

var file_api_committerpb_block_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_committerpb_block_query_proto_goTypes = []any{
	(*BlockNumber)(nil), // 0: committerpb.BlockNumber
	(*TxID)(nil),        // 1: committerpb.TxID
}
var file_api_committerpb_block_query_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_committerpb_block_query_proto_init() }
func file_api_committerpb_block_query_proto_init() {
	if File_api_committerpb_block_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_block_query_proto_rawDesc), len(file_api_committerpb_block_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_committerpb_block_query_proto_goTypes,
		DependencyIndexes: file_api_committerpb_block_query_proto_depIdxs,
		MessageInfos:      file_api_committerpb_block_query_proto_msgTypes,
	}.Build()
	File_api_committerpb_block_query_proto = out.File
	file_api_committerpb_block_query_proto_goTypes = nil
	file_api_committerpb_block_query_proto_depIdxs = nil
}
