//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/committerpb/notify.proto

package committerpb

import (
	applicationpb "github.com/hyperledger/fabric-x-common/api/applicationpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationRequest is sent by the clients to subscribe to events.
type NotificationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TxStatusRequest *TxIDsBatch            `protobuf:"bytes,1,opt,name=tx_status_request,json=txStatusRequest,proto3,oneof" json:"tx_status_request,omitempty"`
	// The timeout duration that applies to ALL the subscriptions in this request.
	// It is non-strict, i.e., it is possible to receive notifications for this request
	// after the timeout has passed.
	// If this field is not set or has a default value (zero), the default would be applied as
	// per the committer's configuration.
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_api_committerpb_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetTxStatusRequest() *TxIDsBatch {
	if x != nil {
		return x.TxStatusRequest
	}
	return nil
}

func (x *NotificationRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// NotificationResponse contains a batch of event details.
// It is pushed to the client via the stream.
type NotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TxStatusEvents []*TxStatus            `protobuf:"bytes,1,rep,name=tx_status_events,json=txStatusEvents,proto3" json:"tx_status_events,omitempty"` // List of transaction status events.
	TimeoutTxIds   []string               `protobuf:"bytes,2,rep,name=timeout_tx_ids,json=timeoutTxIds,proto3" json:"timeout_tx_ids,omitempty"`       // List of timeout events.
	RejectedTxIds  *RejectedTxIds         `protobuf:"bytes,3,opt,name=rejected_tx_ids,json=rejectedTxIds,proto3" json:"rejected_tx_ids,omitempty"`    // List of rejected transaction IDs with a reason.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_api_committerpb_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetTxStatusEvents() []*TxStatus {
	if x != nil {
		return x.TxStatusEvents
	}
	return nil
}

func (x *NotificationResponse) GetTimeoutTxIds() []string {
	if x != nil {
		return x.TimeoutTxIds
	}
	return nil
}

func (x *NotificationResponse) GetRejectedTxIds() *RejectedTxIds {
	if x != nil {
		return x.RejectedTxIds
	}
	return nil
}

// RejectedTxIds contains a list of transaction IDs that were rejected along with the reason.
type RejectedTxIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxIds         []string               `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"` // List of rejected transaction IDs.
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`            // The reason for rejection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectedTxIds) Reset() {
	*x = RejectedTxIds{}
	mi := &file_api_committerpb_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectedTxIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectedTxIds) ProtoMessage() {}

func (x *RejectedTxIds) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectedTxIds.ProtoReflect.Descriptor instead.
func (*RejectedTxIds) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{2}
}

func (x *RejectedTxIds) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

func (x *RejectedTxIds) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// StreamBlocksRequest is sent by clients to subscribe to all committed transactions.
type StreamBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by namespace IDs (OR logic: transaction touches ANY of these namespaces).
	// Empty list means no namespace filtering (all namespaces included).
	FilterNamespaces []string `protobuf:"bytes,1,rep,name=filter_namespaces,json=filterNamespaces,proto3" json:"filter_namespaces,omitempty"`
	// Filter by transaction status (multiple statuses can be specified).
	// Empty list means no status filtering (all statuses included).
	FilterStatus []Status `protobuf:"varint,2,rep,packed,name=filter_status,json=filterStatus,proto3,enum=committerpb.Status" json:"filter_status,omitempty"`
	// Include transaction content (read/write sets) in the response.
	// Default: false (only transaction reference and status).
	IncludeReadWriteSets bool `protobuf:"varint,3,opt,name=include_read_write_sets,json=includeReadWriteSets,proto3" json:"include_read_write_sets,omitempty"`
	// Include endorsements in the response.
	// Default: false (only transaction reference and status).
	IncludeEndorsements bool `protobuf:"varint,4,opt,name=include_endorsements,json=includeEndorsements,proto3" json:"include_endorsements,omitempty"`
	// Include metadata in the response.
	// Default: false (only transaction reference and status).
	IncludeMetadata bool `protobuf:"varint,5,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_api_committerpb_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{3}
}

func (x *StreamBlocksRequest) GetFilterNamespaces() []string {
	if x != nil {
		return x.FilterNamespaces
	}
	return nil
}

func (x *StreamBlocksRequest) GetFilterStatus() []Status {
	if x != nil {
		return x.FilterStatus
	}
	return nil
}

func (x *StreamBlocksRequest) GetIncludeReadWriteSets() bool {
	if x != nil {
		return x.IncludeReadWriteSets
	}
	return false
}

func (x *StreamBlocksRequest) GetIncludeEndorsements() bool {
	if x != nil {
		return x.IncludeEndorsements
	}
	return false
}

func (x *StreamBlocksRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// BlockEvent contains a batch of transaction events from a single block.
type BlockEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The block number from which these transactions originated.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// List of transaction events (may be filtered based on request).
	Events []*TxEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// The hash of the block from which these transactions originated.
	BlockHash []byte `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// The hash of the previous block.
	PrevBlockHash []byte `protobuf:"bytes,4,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockEvent) Reset() {
	*x = BlockEvent{}
	mi := &file_api_committerpb_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEvent) ProtoMessage() {}

func (x *BlockEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEvent.ProtoReflect.Descriptor instead.
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{4}
}

func (x *BlockEvent) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *BlockEvent) GetEvents() []*TxEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *BlockEvent) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockEvent) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

// TxEvent represents a single transaction event.
type TxEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction reference (ID, block number, transaction index).
	Ref *TxRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Transaction commit status.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=committerpb.Status" json:"status,omitempty"`
	// Transaction namespaces (included only if include_read_write_sets is true).
	// If namespace filtering is active, only matching namespaces are included.
	// Empty if not requested or if transaction has no namespaces.
	Namespaces []*applicationpb.TxNamespace `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Transaction endorsements (included only if include_endorsements is true).
	// Empty if not requested or if transaction has no endorsements.
	Endorsements []*applicationpb.Endorsements `protobuf:"bytes,4,rep,name=endorsements,proto3" json:"endorsements,omitempty"`
	// Transaction metadata (included only if include_metadata is true).
	// Empty if not requested or if transaction has no metadata.
	Metadata      [][]byte `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxEvent) Reset() {
	*x = TxEvent{}
	mi := &file_api_committerpb_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxEvent) ProtoMessage() {}

func (x *TxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxEvent.ProtoReflect.Descriptor instead.
func (*TxEvent) Descriptor() ([]byte, []int) {
	return file_api_committerpb_notify_proto_rawDescGZIP(), []int{5}
}

func (x *TxEvent) GetRef() *TxRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *TxEvent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TxEvent) GetNamespaces() []*applicationpb.TxNamespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *TxEvent) GetEndorsements() []*applicationpb.Endorsements {
	if x != nil {
		return x.Endorsements
	}
	return nil
}

func (x *TxEvent) GetMetadata() [][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_committerpb_notify_proto protoreflect.FileDescriptor

const file_api_committerpb_notify_proto_rawDesc = "" +
	"\n" +
	"\x1capi/committerpb/notify.proto\x12\vcommitterpb\x1a\x1egoogle/protobuf/duration.proto\x1a\x19api/committerpb/ref.proto\x1a\x1capi/committerpb/status.proto\x1a api/applicationpb/block_tx.proto\"\xaa\x01\n" +
	"\x13NotificationRequest\x12H\n" +
	"\x11tx_status_request\x18\x01 \x01(\v2\x17.committerpb.TxIDsBatchH\x00R\x0ftxStatusRequest\x88\x01\x01\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeoutB\x14\n" +
	"\x12_tx_status_request\"\xc1\x01\n" +
	"\x14NotificationResponse\x12?\n" +
	"\x10tx_status_events\x18\x01 \x03(\v2\x15.committerpb.TxStatusR\x0etxStatusEvents\x12$\n" +
	"\x0etimeout_tx_ids\x18\x02 \x03(\tR\ftimeoutTxIds\x12B\n" +
	"\x0frejected_tx_ids\x18\x03 \x01(\v2\x1a.committerpb.RejectedTxIdsR\rrejectedTxIds\">\n" +
	"\rRejectedTxIds\x12\x15\n" +
	"\x06tx_ids\x18\x01 \x03(\tR\x05txIds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x91\x02\n" +
	"\x13StreamBlocksRequest\x12+\n" +
	"\x11filter_namespaces\x18\x01 \x03(\tR\x10filterNamespaces\x128\n" +
	"\rfilter_status\x18\x02 \x03(\x0e2\x13.committerpb.StatusR\ffilterStatus\x125\n" +
	"\x17include_read_write_sets\x18\x03 \x01(\bR\x14includeReadWriteSets\x121\n" +
	"\x14include_endorsements\x18\x04 \x01(\bR\x13includeEndorsements\x12)\n" +
	"\x10include_metadata\x18\x05 \x01(\bR\x0fincludeMetadata\"\xa4\x01\n" +
	"\n" +
	"BlockEvent\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12,\n" +
	"\x06events\x18\x02 \x03(\v2\x14.committerpb.TxEventR\x06events\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12&\n" +
	"\x0fprev_block_hash\x18\x04 \x01(\fR\rprevBlockHash\"\xf5\x01\n" +
	"\aTxEvent\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.committerpb.TxRefR\x03ref\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.committerpb.StatusR\x06status\x12:\n" +
	"\n" +
	"namespaces\x18\x03 \x03(\v2\x1a.applicationpb.TxNamespaceR\n" +
	"namespaces\x12?\n" +
	"\fendorsements\x18\x04 \x03(\v2\x1b.applicationpb.EndorsementsR\fendorsements\x12\x1a\n" +
	"\bmetadata\x18\x05 \x03(\fR\bmetadataB8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_notify_proto_rawDescOnce sync.Once
	file_api_committerpb_notify_proto_rawDescData []byte
)

func file_api_committerpb_notify_proto_rawDescGZIP() []byte {
	file_api_committerpb_notify_proto_rawDescOnce.Do(func() {
		file_api_committerpb_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_notify_proto_rawDesc), len(file_api_committerpb_notify_proto_rawDesc)))
	})
	return file_api_committerpb_notify_proto_rawDescData
}

var file_api_committerpb_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_committerpb_notify_proto_goTypes = []any{
	(*NotificationRequest)(nil),        // 0: committerpb.NotificationRequest
	(*NotificationResponse)(nil),       // 1: committerpb.NotificationResponse
	(*RejectedTxIds)(nil),              // 2: committerpb.RejectedTxIds
	(*StreamBlocksRequest)(nil),        // 3: committerpb.StreamBlocksRequest
	(*BlockEvent)(nil),                 // 4: committerpb.BlockEvent
	(*TxEvent)(nil),                    // 5: committerpb.TxEvent
	(*TxIDsBatch)(nil),                 // 6: committerpb.TxIDsBatch
	(*durationpb.Duration)(nil),        // 7: google.protobuf.Duration
	(*TxStatus)(nil),                   // 8: committerpb.TxStatus
	(Status)(0),                        // 9: committerpb.Status
	(*TxRef)(nil),                      // 10: committerpb.TxRef
	(*applicationpb.TxNamespace)(nil),  // 11: applicationpb.TxNamespace
	(*applicationpb.Endorsements)(nil), // 12: applicationpb.Endorsements
}
var file_api_committerpb_notify_proto_depIdxs = []int32{
	6,  // 0: committerpb.NotificationRequest.tx_status_request:type_name -> committerpb.TxIDsBatch
	7,  // 1: committerpb.NotificationRequest.timeout:type_name -> google.protobuf.Duration
	8,  // 2: committerpb.NotificationResponse.tx_status_events:type_name -> committerpb.TxStatus
	2,  // 3: committerpb.NotificationResponse.rejected_tx_ids:type_name -> committerpb.RejectedTxIds
	9,  // 4: committerpb.StreamBlocksRequest.filter_status:type_name -> committerpb.Status
	5,  // 5: committerpb.BlockEvent.events:type_name -> committerpb.TxEvent
	10, // 6: committerpb.TxEvent.ref:type_name -> committerpb.TxRef
	9,  // 7: committerpb.TxEvent.status:type_name -> committerpb.Status
	11, // 8: committerpb.TxEvent.namespaces:type_name -> applicationpb.TxNamespace
	12, // 9: committerpb.TxEvent.endorsements:type_name -> applicationpb.Endorsements
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_committerpb_notify_proto_init() }
func file_api_committerpb_notify_proto_init() {
	if File_api_committerpb_notify_proto != nil {
		return
	}
	file_api_committerpb_ref_proto_init()
	file_api_committerpb_status_proto_init()
	file_api_committerpb_notify_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_notify_proto_rawDesc), len(file_api_committerpb_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_committerpb_notify_proto_goTypes,
		DependencyIndexes: file_api_committerpb_notify_proto_depIdxs,
		MessageInfos:      file_api_committerpb_notify_proto_msgTypes,
	}.Build()
	File_api_committerpb_notify_proto = out.File
	file_api_committerpb_notify_proto_goTypes = nil
	file_api_committerpb_notify_proto_depIdxs = nil
}
