//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// AIP-135 models Delete as a resource operation: it expects a `name` field and a
// `google.api.method_signature` annotation. DeleteDBCloneForSnapshot is not a
// resource delete -- it drops the database clone belonging to a snapshot that is
// identified by its transaction ID, and `tx_id` is the _snapshot namespace row
// key used throughout the committer. Renaming that field to `name` would obscure
// it, so the three AIP-135 rules are disabled for this file.
// (-- api-linter: core::0135::method-signature=disabled --)
// (-- api-linter: core::0135::request-unknown-fields=disabled --)
// (-- api-linter: core::0135::request-name-required=disabled --)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/committerpb/sidecar.proto

package committerpb

import (
	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeleteDBCloneForSnapshotRequest identifies the snapshot whose database clone is dropped.
type DeleteDBCloneForSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID of the snapshot transaction, the _snapshot namespace row key.
	TxId          string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDBCloneForSnapshotRequest) Reset() {
	*x = DeleteDBCloneForSnapshotRequest{}
	mi := &file_api_committerpb_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDBCloneForSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDBCloneForSnapshotRequest) ProtoMessage() {}

func (x *DeleteDBCloneForSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_committerpb_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDBCloneForSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteDBCloneForSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_committerpb_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteDBCloneForSnapshotRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_api_committerpb_sidecar_proto protoreflect.FileDescriptor

const file_api_committerpb_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/committerpb/sidecar.proto\x12\vcommitterpb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\x1a\x13common/ledger.proto\x1a!api/committerpb/block_query.proto\x1a\x1capi/committerpb/notify.proto\"6\n" +
	"\x1fDeleteDBCloneForSnapshotRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId2\x8a\x04\n" +
	"\x0eSidecarService\x12C\n" +
	"\x11GetBlockchainInfo\x12\x16.google.protobuf.Empty\x1a\x16.common.BlockchainInfo\x12;\n" +
	"\x10GetBlockByNumber\x12\x18.committerpb.BlockNumber\x1a\r.common.Block\x122\n" +
	"\x0eGetBlockByTxID\x12\x11.committerpb.TxID\x1a\r.common.Block\x120\n" +
	"\tGetTxByID\x12\x11.committerpb.TxID\x1a\x10.common.Envelope\x12a\n" +
	"\x16OpenNotificationStream\x12 .committerpb.NotificationRequest\x1a!.committerpb.NotificationResponse(\x010\x01\x12K\n" +
	"\fStreamBlocks\x12 .committerpb.StreamBlocksRequest\x1a\x17.committerpb.BlockEvent0\x01\x12`\n" +
	"\x18DeleteDBCloneForSnapshot\x12,.committerpb.DeleteDBCloneForSnapshotRequest\x1a\x16.google.protobuf.EmptyB8Z6github.com/hyperledger/fabric-x-common/api/committerpbb\x06proto3"

var (
	file_api_committerpb_sidecar_proto_rawDescOnce sync.Once
	file_api_committerpb_sidecar_proto_rawDescData []byte
)

func file_api_committerpb_sidecar_proto_rawDescGZIP() []byte {
	file_api_committerpb_sidecar_proto_rawDescOnce.Do(func() {
		file_api_committerpb_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_committerpb_sidecar_proto_rawDesc), len(file_api_committerpb_sidecar_proto_rawDesc)))
	})
	return file_api_committerpb_sidecar_proto_rawDescData
}

var file_api_committerpb_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_committerpb_sidecar_proto_goTypes = []any{
	(*DeleteDBCloneForSnapshotRequest)(nil), // 0: committerpb.DeleteDBCloneForSnapshotRequest
	(*emptypb.Empty)(nil),                   // 1: google.protobuf.Empty
	(*BlockNumber)(nil),                     // 2: committerpb.BlockNumber
	(*TxID)(nil),                            // 3: committerpb.TxID
	(*NotificationRequest)(nil),             // 4: committerpb.NotificationRequest
	(*StreamBlocksRequest)(nil),             // 5: committerpb.StreamBlocksRequest
	(*common.BlockchainInfo)(nil),           // 6: common.BlockchainInfo
	(*common.Block)(nil),                    // 7: common.Block
	(*common.Envelope)(nil),                 // 8: common.Envelope
	(*NotificationResponse)(nil),            // 9: committerpb.NotificationResponse
	(*BlockEvent)(nil),                      // 10: committerpb.BlockEvent
}
var file_api_committerpb_sidecar_proto_depIdxs = []int32{
	1,  // 0: committerpb.SidecarService.GetBlockchainInfo:input_type -> google.protobuf.Empty
	2,  // 1: committerpb.SidecarService.GetBlockByNumber:input_type -> committerpb.BlockNumber
	3,  // 2: committerpb.SidecarService.GetBlockByTxID:input_type -> committerpb.TxID
	3,  // 3: committerpb.SidecarService.GetTxByID:input_type -> committerpb.TxID
	4,  // 4: committerpb.SidecarService.OpenNotificationStream:input_type -> committerpb.NotificationRequest
	5,  // 5: committerpb.SidecarService.StreamBlocks:input_type -> committerpb.StreamBlocksRequest
	0,  // 6: committerpb.SidecarService.DeleteDBCloneForSnapshot:input_type -> committerpb.DeleteDBCloneForSnapshotRequest
	6,  // 7: committerpb.SidecarService.GetBlockchainInfo:output_type -> common.BlockchainInfo
	7,  // 8: committerpb.SidecarService.GetBlockByNumber:output_type -> common.Block
	7,  // 9: committerpb.SidecarService.GetBlockByTxID:output_type -> common.Block
	8,  // 10: committerpb.SidecarService.GetTxByID:output_type -> common.Envelope
	9,  // 11: committerpb.SidecarService.OpenNotificationStream:output_type -> committerpb.NotificationResponse
	10, // 12: committerpb.SidecarService.StreamBlocks:output_type -> committerpb.BlockEvent
	1,  // 13: committerpb.SidecarService.DeleteDBCloneForSnapshot:output_type -> google.protobuf.Empty
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_committerpb_sidecar_proto_init() }
func file_api_committerpb_sidecar_proto_init() {
	if File_api_committerpb_sidecar_proto != nil {
		return
	}
	file_api_committerpb_block_query_proto_init()
	file_api_committerpb_notify_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_committerpb_sidecar_proto_rawDesc), len(file_api_committerpb_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_committerpb_sidecar_proto_goTypes,
		DependencyIndexes: file_api_committerpb_sidecar_proto_depIdxs,
		MessageInfos:      file_api_committerpb_sidecar_proto_msgTypes,
	}.Build()
	File_api_committerpb_sidecar_proto = out.File
	file_api_committerpb_sidecar_proto_goTypes = nil
	file_api_committerpb_sidecar_proto_depIdxs = nil
}
