//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// AIP-135 models Delete as a resource operation: it expects a `name` field and a
// `google.api.method_signature` annotation. DeleteDBCloneForSnapshot is not a
// resource delete -- it drops the database clone belonging to a snapshot that is
// identified by its transaction ID, and `tx_id` is the _snapshot namespace row
// key used throughout the committer. Renaming that field to `name` would obscure
// it, so the three AIP-135 rules are disabled for this file.
// (-- api-linter: core::0135::method-signature=disabled --)
// (-- api-linter: core::0135::request-unknown-fields=disabled --)
// (-- api-linter: core::0135::request-name-required=disabled --)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: api/committerpb/sidecar.proto

package committerpb

import (
	context "context"
	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SidecarService_GetBlockchainInfo_FullMethodName        = "/committerpb.SidecarService/GetBlockchainInfo"
	SidecarService_GetBlockByNumber_FullMethodName         = "/committerpb.SidecarService/GetBlockByNumber"
	SidecarService_GetBlockByTxID_FullMethodName           = "/committerpb.SidecarService/GetBlockByTxID"
	SidecarService_GetTxByID_FullMethodName                = "/committerpb.SidecarService/GetTxByID"
	SidecarService_OpenNotificationStream_FullMethodName   = "/committerpb.SidecarService/OpenNotificationStream"
	SidecarService_StreamBlocks_FullMethodName             = "/committerpb.SidecarService/StreamBlocks"
	SidecarService_DeleteDBCloneForSnapshot_FullMethodName = "/committerpb.SidecarService/DeleteDBCloneForSnapshot"
)

// SidecarServiceClient is the client API for SidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SidecarService is the single service backing sidecar client traffic: block
// queries, event notifications, and snapshot-clone administration. New sidecar
// RPCs belong here rather than in a new service.
//
// Fabric block delivery is deliberately not part of this service. It stays on
// the Fabric `protos.Deliver` service so Fabric clients can dial the sidecar
// unchanged; one sidecar object backs both services.
type SidecarServiceClient interface {
	// Block store reads. Previously BlockQueryService.
	GetBlockchainInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.BlockchainInfo, error)
	GetBlockByNumber(ctx context.Context, in *BlockNumber, opts ...grpc.CallOption) (*common.Block, error)
	GetBlockByTxID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Block, error)
	GetTxByID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Envelope, error)
	// Event subscriptions. Previously Notifier.
	OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationRequest, NotificationResponse], error)
	StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error)
	// Snapshot-clone administration. The committer answers UNIMPLEMENTED until
	// the clone-deletion pipeline lands.
	DeleteDBCloneForSnapshot(ctx context.Context, in *DeleteDBCloneForSnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarServiceClient(cc grpc.ClientConnInterface) SidecarServiceClient {
	return &sidecarServiceClient{cc}
}

func (c *sidecarServiceClient) GetBlockchainInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*common.BlockchainInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.BlockchainInfo)
	err := c.cc.Invoke(ctx, SidecarService_GetBlockchainInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) GetBlockByNumber(ctx context.Context, in *BlockNumber, opts ...grpc.CallOption) (*common.Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Block)
	err := c.cc.Invoke(ctx, SidecarService_GetBlockByNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) GetBlockByTxID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Block)
	err := c.cc.Invoke(ctx, SidecarService_GetBlockByTxID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) GetTxByID(ctx context.Context, in *TxID, opts ...grpc.CallOption) (*common.Envelope, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Envelope)
	err := c.cc.Invoke(ctx, SidecarService_GetTxByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) OpenNotificationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NotificationRequest, NotificationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SidecarService_ServiceDesc.Streams[0], SidecarService_OpenNotificationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotificationRequest, NotificationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_OpenNotificationStreamClient = grpc.BidiStreamingClient[NotificationRequest, NotificationResponse]

func (c *sidecarServiceClient) StreamBlocks(ctx context.Context, in *StreamBlocksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SidecarService_ServiceDesc.Streams[1], SidecarService_StreamBlocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBlocksRequest, BlockEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_StreamBlocksClient = grpc.ServerStreamingClient[BlockEvent]

func (c *sidecarServiceClient) DeleteDBCloneForSnapshot(ctx context.Context, in *DeleteDBCloneForSnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SidecarService_DeleteDBCloneForSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarServiceServer is the server API for SidecarService service.
// All implementations must embed UnimplementedSidecarServiceServer
// for forward compatibility.
//
// SidecarService is the single service backing sidecar client traffic: block
// queries, event notifications, and snapshot-clone administration. New sidecar
// RPCs belong here rather than in a new service.
//
// Fabric block delivery is deliberately not part of this service. It stays on
// the Fabric `protos.Deliver` service so Fabric clients can dial the sidecar
// unchanged; one sidecar object backs both services.
type SidecarServiceServer interface {
	// Block store reads. Previously BlockQueryService.
	GetBlockchainInfo(context.Context, *emptypb.Empty) (*common.BlockchainInfo, error)
	GetBlockByNumber(context.Context, *BlockNumber) (*common.Block, error)
	GetBlockByTxID(context.Context, *TxID) (*common.Block, error)
	GetTxByID(context.Context, *TxID) (*common.Envelope, error)
	// Event subscriptions. Previously Notifier.
	OpenNotificationStream(grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]) error
	StreamBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockEvent]) error
	// Snapshot-clone administration. The committer answers UNIMPLEMENTED until
	// the clone-deletion pipeline lands.
	DeleteDBCloneForSnapshot(context.Context, *DeleteDBCloneForSnapshotRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSidecarServiceServer()
}

// UnimplementedSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarServiceServer struct{}

func (UnimplementedSidecarServiceServer) GetBlockchainInfo(context.Context, *emptypb.Empty) (*common.BlockchainInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockchainInfo not implemented")
}
func (UnimplementedSidecarServiceServer) GetBlockByNumber(context.Context, *BlockNumber) (*common.Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByNumber not implemented")
}
func (UnimplementedSidecarServiceServer) GetBlockByTxID(context.Context, *TxID) (*common.Block, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlockByTxID not implemented")
}
func (UnimplementedSidecarServiceServer) GetTxByID(context.Context, *TxID) (*common.Envelope, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTxByID not implemented")
}
func (UnimplementedSidecarServiceServer) OpenNotificationStream(grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenNotificationStream not implemented")
}
func (UnimplementedSidecarServiceServer) StreamBlocks(*StreamBlocksRequest, grpc.ServerStreamingServer[BlockEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedSidecarServiceServer) DeleteDBCloneForSnapshot(context.Context, *DeleteDBCloneForSnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDBCloneForSnapshot not implemented")
}
func (UnimplementedSidecarServiceServer) mustEmbedUnimplementedSidecarServiceServer() {}
func (UnimplementedSidecarServiceServer) testEmbeddedByValue()                        {}

// UnsafeSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarServiceServer will
// result in compilation errors.
type UnsafeSidecarServiceServer interface {
	mustEmbedUnimplementedSidecarServiceServer()
}

func RegisterSidecarServiceServer(s grpc.ServiceRegistrar, srv SidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarService_ServiceDesc, srv)
}

func _SidecarService_GetBlockchainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).GetBlockchainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_GetBlockchainInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).GetBlockchainInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_GetBlockByNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).GetBlockByNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_GetBlockByNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).GetBlockByNumber(ctx, req.(*BlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_GetBlockByTxID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).GetBlockByTxID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_GetBlockByTxID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).GetBlockByTxID(ctx, req.(*TxID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_GetTxByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).GetTxByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_GetTxByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).GetTxByID(ctx, req.(*TxID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_OpenNotificationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SidecarServiceServer).OpenNotificationStream(&grpc.GenericServerStream[NotificationRequest, NotificationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_OpenNotificationStreamServer = grpc.BidiStreamingServer[NotificationRequest, NotificationResponse]

func _SidecarService_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBlocksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SidecarServiceServer).StreamBlocks(m, &grpc.GenericServerStream[StreamBlocksRequest, BlockEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SidecarService_StreamBlocksServer = grpc.ServerStreamingServer[BlockEvent]

func _SidecarService_DeleteDBCloneForSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDBCloneForSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).DeleteDBCloneForSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_DeleteDBCloneForSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).DeleteDBCloneForSnapshot(ctx, req.(*DeleteDBCloneForSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarService_ServiceDesc is the grpc.ServiceDesc for SidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "committerpb.SidecarService",
	HandlerType: (*SidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockchainInfo",
			Handler:    _SidecarService_GetBlockchainInfo_Handler,
		},
		{
			MethodName: "GetBlockByNumber",
			Handler:    _SidecarService_GetBlockByNumber_Handler,
		},
		{
			MethodName: "GetBlockByTxID",
			Handler:    _SidecarService_GetBlockByTxID_Handler,
		},
		{
			MethodName: "GetTxByID",
			Handler:    _SidecarService_GetTxByID_Handler,
		},
		{
			MethodName: "DeleteDBCloneForSnapshot",
			Handler:    _SidecarService_DeleteDBCloneForSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenNotificationStream",
			Handler:       _SidecarService_OpenNotificationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamBlocks",
			Handler:       _SidecarService_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/committerpb/sidecar.proto",
}
